### ISSUE TITLE
transfer_url is null

### ISSUE THREAD

**Issue by DevCubeHD** [echeese/TradeOfferLib#4]
Line 122: String transfer_url;
Line 251: fetch(loginJson.transfer_url, "POST", data, false );

transfer_url is null... can you help me? Its set nowhere

**Comment by echeese** [comment]
This project is no longer maintained, sorry. If you fix it, please send a pull request.

**Comment by DevCubeHD** [comment]
Hey Ryan,
bitte befolge die Anweisungen der install.txt :)
Ich nehme an du hast noch keine Gruppe und keinen User erstellt



Felix Gaebler
Developer, VoxelBoxStudios
Project: CloudSystem 2.0
Website: https://voxelboxstudios.com
E-Mail:   feligaeb@web.de
*CloudSystem 2.0*


2016-05-04 21:43 GMT+02:00 Ryan Speets <notifications@github.com>:

**Comment by DevCubeHD** [comment]
Okay my google mail just sends mail here. .wow :D

I had just rewritten your API.. but the last thing I dont know and that dont works is "g_ulTradePartnerSteamID" in the trade class... maybe you can help me with this last thing and I can publish here the complete rewrite
